import { Activity, BrainCircuit, FileUp, Gauge, Image, Layers3, LockKeyhole, ScanSearch, ShieldAlert, Stethoscope } from 'lucide-react'
import { useEffect, useState } from 'react'
import { getPerformance } from '../services/api'

const steps = [
  [FileUp,'1','Upload X-ray','Select a JPEG or PNG chest X-ray. The file is validated before model access.'],
  [Image,'2','Image preprocessing','The same grayscale-to-RGB, resize, and normalization pipeline used during training is applied.'],
  [BrainCircuit,'3','Deep learning analysis','The selected convolutional network generates a calibrated prediction score.'],
  [ScanSearch,'4','Review the result','See the classification, uncertainty state, score distribution, and attention map.'],
]

export function HowItWorks() { return <section id="how-it-works" className="section-pad bg-white"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="section-heading"><span className="eyebrow">Transparent workflow</span><h2>From upload to research result</h2><p>One deterministic inference pipeline keeps training and application behavior aligned.</p></div><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{steps.map(([Icon,n,title,text])=><article key={n} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-card"><div className="flex items-center justify-between"><span className="grid h-11 w-11 place-items-center rounded-xl bg-teal-50 text-teal-700"><Icon size={21}/></span><span className="text-3xl font-bold text-teal-100">{n}</span></div><h3 className="mt-5 text-lg font-bold text-ink">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></div></section> }

const metricNames = { accuracy:'Accuracy', precision:'Precision', recall_sensitivity:'Sensitivity', specificity:'Specificity', f1:'F1 score', roc_auc:'ROC–AUC' }
export function Performance() {
  const [data,setData]=useState(null)
  useEffect(()=>{const c=new AbortController(); getPerformance(c.signal).then(setData).catch(()=>setData({test_metrics:null})); return()=>c.abort()},[])
  const metrics=data?.test_metrics
  return <section id="performance" className="section-pad bg-ink text-white"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="max-w-3xl"><span className="eyebrow !bg-white/10 !text-teal-100">Evidence, not claims</span><h2 className="mt-5 text-3xl font-bold tracking-tight sm:text-4xl">Model performance</h2><p className="mt-4 leading-7 text-slate-300">Values appear only after the selected model is evaluated once on the untouched patient-level test partition. No demonstration numbers are hardcoded.</p></div>
    {metrics ? <div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(metricNames).map(([key,label])=><div key={key} className="rounded-2xl border border-white/10 bg-white/5 p-5"><p className="text-sm text-teal-100">{label}</p><p className="mt-2 text-3xl font-bold tabular-nums">{(metrics[key]*100).toFixed(1)}%</p></div>)}</div> : <div className="mt-10 rounded-2xl border border-white/15 bg-white/5 p-6"><div className="flex gap-4"><Gauge className="shrink-0 text-teal-200"/><div><h3 className="font-bold">Final evaluation pending</h3><p className="mt-2 text-sm leading-6 text-slate-300">The training pipeline has not yet produced a verified final test report. This state is intentional: unmeasured values are never fabricated.</p></div></div></div>}
    <div className="mt-8 grid gap-4 text-sm text-slate-300 md:grid-cols-3"><p className="rounded-xl border border-white/10 p-4"><strong className="block text-white">Architecture</strong>{data?.model || 'Selected after validation comparison'}</p><p className="rounded-xl border border-white/10 p-4"><strong className="block text-white">Input</strong>{data?.image_size ? `${data.image_size[0]} × ${data.image_size[1]} grayscale-derived RGB` : '224 × 224 target pipeline'}</p><p className="rounded-xl border border-white/10 p-4"><strong className="block text-white">Validation policy</strong>Patient-grouped, duplicate-aware, fixed seed 42</p></div>
  </div></section>
}

export function About() { return <section id="about" className="section-pad bg-mist"><div className="mx-auto grid max-w-7xl gap-10 px-5 lg:grid-cols-[.85fr_1.15fr] lg:px-8"><div><span className="eyebrow">About the project</span><h2 className="mt-5 text-3xl font-bold tracking-tight text-ink sm:text-4xl">Built for reproducible research</h2><p className="mt-4 leading-7 text-slate-600">PneumoAI compares a baseline CNN with transfer-learning architectures, selects on validation evidence, calibrates scores, then evaluates once on a held-out test set.</p></div><div className="grid gap-4 sm:grid-cols-2">{[[Layers3,'Leakage-aware splits','Exact duplicates are removed and patients are kept within a single partition.'],[Activity,'Clinical metrics','Sensitivity, specificity, F1, ROC–AUC, PR–AUC, and false negatives accompany accuracy.'],[LockKeyhole,'Privacy by design','Inference operates in memory; uploaded images are not intentionally written to disk.'],[ShieldAlert,'Bounded claims','Scores are model outputs—not the probability that a patient truly has pneumonia.']].map(([Icon,title,text])=><article key={title} className="rounded-2xl border border-teal-100 bg-white p-5 shadow-card"><Icon className="text-teal-700"/><h3 className="mt-4 font-bold text-ink">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></div></section> }

export function Disclaimer() { return <section id="disclaimer" className="border-y border-amber-200 bg-amber-50"><div className="mx-auto flex max-w-7xl flex-col gap-5 px-5 py-10 sm:flex-row lg:px-8"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-amber-200 text-amber-600"><Stethoscope/></span><div><h2 className="text-xl font-bold text-ink">Medical disclaimer</h2><p className="mt-2 max-w-4xl leading-7 text-slate-700">This AI system is an educational/research prototype and does not provide a medical diagnosis. Predictions may be incorrect. Chest X-rays and medical symptoms should be reviewed by a qualified healthcare professional.</p><p className="mt-2 font-semibold text-amber-900">Please consult a qualified healthcare professional for medical interpretation.</p></div></div></section> }
